<?php

return [
    'cookie' => 'fine_save',

    'sip' => [
        'base_power' => 1,
        'max_per_request' => 40,
        'combo_window_ms' => 1200,
        'combo_cap' => 5,
        'crit_multiplier' => 5,
        'crit_base_chance' => 0.12,
        'crit_chance_per_level' => 0.03,
        'unlit_multiplier' => 0.3,
        'panic_multiplier' => 0.5,
        'heat_per_sip' => 0.4,
    ],

    'heat' => [
        'max' => 100,
        'decay_per_sec' => 1.2,
        'bonus_divisor' => 250,
    ],

    'idle' => [
        'max_offline_seconds' => 8 * 3600,
        'machine_per_level' => 0.4,
        'merch_per_level' => 0.7,
    ],

    'buffs' => [
        'viral_seconds' => 20,
        'viral_multiplier' => 3,
        'livestream_seconds' => 20,
        'livestream_multiplier' => 3,
        'livestream_cooldown' => 45,
        'ad_seconds' => 60,
        'ad_multiplier' => 2,
        'panic_seconds' => 25,
        'fine_pass_multiplier' => 1.15,
    ],

    'stages' => [
        [
            'id' => 'kitchen',
            'title' => 'Кухня в хрущёвке',
            'threshold' => 0,
            'caption' => 'Чайник свистит, проводка искрит. Соседи сверху уже стучат. Норм.',
        ],
        [
            'id' => 'office',
            'title' => 'Планёрка в Zoom',
            'threshold' => 60,
            'caption' => 'Камера выключена. «Вас не слышно». Квартира горит. Работаем.',
        ],
        [
            'id' => 'city',
            'title' => 'Пробки на МКАД',
            'threshold' => 280,
            'caption' => 'Стоим. Горим. По радио обещают разъехаться к пятнице.',
        ],
        [
            'id' => 'internet',
            'title' => 'Залетело в рекомендации',
            'threshold' => 1200,
            'caption' => 'Тётя Люда репостнула в семейный чат. Три соседки уже «жиза».',
        ],
        [
            'id' => 'cosmos',
            'title' => 'На орбите тоже норм',
            'threshold' => 5000,
            'caption' => 'Роскосмос молчит. Кофе в невесомости. Держимся.',
        ],
    ],

    'upgrades' => [
        'mug' => [
            'name' => 'Кружка из Fix Price',
            'blurb' => '+1 норм за глоток. Самая честная покупка в этом доме.',
            'icon' => 'mug',
            'mechanic' => false,
            'max' => 40,
            'base_cost' => 10,
            'cost_mult' => 1.17,
            'unlock_lifetime' => 0,
        ],
        'machine' => [
            'name' => 'Кофемашина с ресепшена',
            'blurb' => 'Сама наливает, как в офисе. Появляется доход без кликов.',
            'icon' => 'machine',
            'mechanic' => true,
            'max' => 25,
            'base_cost' => 35,
            'cost_mult' => 1.2,
            'unlock_lifetime' => 8,
        ],
        'nervous' => [
            'name' => 'Нервный глоток',
            'blurb' => 'Кликай быстро — комбо до ×5, как ответы в общем чате до 9:00.',
            'icon' => 'combo',
            'mechanic' => true,
            'max' => 1,
            'base_cost' => 50,
            'cost_mult' => 1,
            'unlock_lifetime' => 25,
        ],
        'espresso' => [
            'name' => 'Двойной с заправки',
            'blurb' => 'Шанс критического глотка ×5. Иногда везёт, как с кэшбэком.',
            'icon' => 'crit',
            'mechanic' => true,
            'max' => 8,
            'base_cost' => 80,
            'cost_mult' => 1.28,
            'unlock_lifetime' => 70,
        ],
        'extinguisher' => [
            'name' => 'Огнетушитель с Авито',
            'blurb' => 'Кризисы забирают меньше норма. Тушить всё равно никто не будет — стоит для интерьера.',
            'icon' => 'extinguisher',
            'mechanic' => false,
            'max' => 5,
            'base_cost' => 120,
            'cost_mult' => 1.4,
            'unlock_lifetime' => 120,
        ],
        'stream' => [
            'name' => 'Сторис «у нас уют»',
            'blurb' => 'Кнопка «В эфир»: 20 сек ×3 норма, потом откат. Прямой эфир как во VK.',
            'icon' => 'stream',
            'mechanic' => true,
            'max' => 1,
            'base_cost' => 200,
            'cost_mult' => 1,
            'unlock_lifetime' => 60,
            'unlock_stage' => 'office',
        ],
        'merch' => [
            'name' => 'Футболки на WB',
            'blurb' => 'Автопродажа принта «всё нормально». Второй пассивный доход, как у блогера.',
            'icon' => 'merch',
            'mechanic' => false,
            'max' => 20,
            'base_cost' => 250,
            'cost_mult' => 1.22,
            'unlock_lifetime' => 280,
            'unlock_stage' => 'city',
        ],
    ],

    'events' => [
        'viral' => [
            'kind' => 'bonus',
            'title' => 'Залетело в семейный чат',
            'body' => 'Тётя Люда скинула кружок: «это ты???». Хайп, стыд, ×3 норма на 20 секунд.',
            'cta' => 'Норм, пусть смотрят',
        ],
        'inspection' => [
            'kind' => 'crisis',
            'title' => 'УК пишет в домовой чат',
            'body' => '«Уважаемые жильцы, у вас дым из окна». Инспектор уже в лифте. Улыбаемся и платим.',
            'cta' => 'Оплатить квитанцию',
        ],
        'rain' => [
            'kind' => 'twist',
            'title' => 'Соседи сверху затопили',
            'body' => 'Огонь потух. Без огня мем не работает, кофемашина молчит. Нужно снова «случайно» включить чайник.',
            'cta' => 'Включить чайник',
        ],
        'panic' => [
            'kind' => 'penalty',
            'title' => 'Мама: «ты как?»',
            'body' => 'На секунду стало не норм. Глотки слабее, пока не капнешь корвалол.',
            'cta' => 'Капнуть корвалол',
        ],
        'cat' => [
            'kind' => 'bonus',
            'title' => 'Дворовый кот как к себе',
            'body' => 'Зашёл, сел на подоконник, смотрит на пожар без эмоций. Настоящий сосед. Бонусный норм.',
            'cta' => 'Насыпать Whiskas',
        ],
    ],

    'monetization' => [
        'fine_pass' => [
            'name' => 'Боевой пропуск «Норм+»',
            'price_label' => '299 ₽ · СБП · демо',
            'blurb' => 'Как в мобилках: +15% ко всему норму и значок «держимся». СБП не списывает — это витрина.',
            'type' => 'pass',
        ],
        'insurance' => [
            'name' => 'Страховка «Не горит»',
            'price_label' => '149 ₽ · МИР · демо',
            'blurb' => 'Следующие 3 кризиса не забирают норм. Классика российских казуалок: заплати, чтобы не бесило.',
            'type' => 'consumable',
        ],
        'starter' => [
            'name' => 'Набор новичка',
            'price_label' => '99 ₽ · демо',
            'blurb' => '+150 норма и золотая кружка. Тот самый пак за 99 ₽, без которого «ну никак».',
            'type' => 'iap',
        ],
        'ad_boost' => [
            'name' => 'Ролик VK ×2',
            'price_label' => 'бесплатно · демо',
            'blurb' => '4 секунды «рекламы» — минута двойного норма. Так живут бесплатные игры в Рунете.',
            'type' => 'ad',
        ],
    ],
];
